-- Flyway chạy các file V<số>__<mô_tả>.sql theo thứ tự, mỗi file đúng một lần.
-- Không sửa file đã chạy rồi, muốn đổi cấu trúc thì thêm file V2, V3...
-- Cú pháp dưới đây chạy được trên cả PostgreSQL (prod) và H2 (dev).

CREATE TABLE todos (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    completed   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    version     BIGINT       NOT NULL DEFAULT 0
);

CREATE INDEX idx_todos_completed  ON todos (completed);
CREATE INDEX idx_todos_created_at ON todos (created_at);
