-- Hộp thư đi (transactional outbox): sự kiện ghi cùng giao dịch với todo, OutboxRelay đẩy sang Kafka rồi
-- đánh dấu published_at. Cú pháp chạy được trên cả PostgreSQL và H2.
-- payload là VARCHAR chứ không phải TEXT: H2 coi TEXT là CLOB và Hibernate (ddl-auto=validate) sẽ báo lệch kiểu.

CREATE TABLE outbox_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id BIGINT       NOT NULL,
    owner_id     BIGINT,
    event_type   VARCHAR(40)  NOT NULL,
    payload      VARCHAR(2000) NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE
);

-- Truy vấn nóng nhất: "các dòng chưa gửi, theo id tăng dần".
CREATE INDEX idx_outbox_events_published_at ON outbox_events (published_at, id);
